"""Validate a Notion sync report generated by sync_notion_knowledge.py."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate Notion sync report")
    parser.add_argument("--report", required=True)
    parser.add_argument("--strict-schema", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    report = json.loads(Path(args.report).read_text(encoding="utf-8"))
    errors = int(report.get("error_count") or 0)
    warnings = int(report.get("warning_count") or 0)
    print(
        json.dumps(
            {
                "target": report.get("target"),
                "menu_count": report.get("menu_count"),
                "store_count": report.get("store_count"),
                "public_menu_count": report.get("public_menu_count"),
                "public_store_faq_count": report.get("public_store_faq_count"),
                "public_knowledge": report.get("public_knowledge", {}),
                "error_count": errors,
                "warning_count": warnings,
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    if args.strict_schema and errors:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
